services:
  deploy-table:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        awsKey: ${aws_access_key_id}
        awsSecret: ${aws_secret_access_key}
        awsSessionToken: ${aws_session_token}
    volumes:
      - ./app/:/app/
    working_dir: /app
    command: sh -c "yarn install && sls deploy --config serverless-table.yml --stage dev"
    profiles:
      - deploy

  app:
    image: ${container_name}
    container_name: ${container_name}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        awsKey: ${aws_access_key_id}
        awsSecret: ${aws_secret_access_key}
        awsSessionToken: ${aws_session_token}
        environment: ${environment}
    volumes:
      - ./app/:/app/
    ports:
      - "3000:3000"
