registerForm:
  handler: src/formularios/infrastructure/http/RegisterFormularioHandler.register
  name: ${self:service}-register-${self:provider.stage}
  events:
    - httpApi:
        path: /formularios
        method: post

listForms:
  handler: src/formularios/infrastructure/http/ListFormulariosHandler.list
  name: ${self:service}-list-${self:provider.stage}
  events:
    - httpApi:
        path: /formularios
        method: get
